### ISSUE TITLE
Change css btn-xs to btn-sm

### ISSUE THREAD

**Issue by skalec** [hudson-trading/netbox-nagios#8]
Hello I found the buttons to big. When you change the class btn_sx to btn_sm it looks like better

**Comment by fabi125** [comment]
Thanks for your feedback. Are you running Netbox 3.0?
I noticed that that will cause the buttons to be bigger than the other UI buttons.
I should have an update for that available soon.

**Comment by skalec** [comment]
Oh sry i forgot. Yes i using netbox 3.1.
